"""
Output & Action Validation Data Models for AgentShield.
"""

import time
import uuid
from enum import Enum
from typing import Dict, Any, List, Optional
from pydantic import BaseModel, Field

from agentshield.context.models import SecurityDecision, TrustLevel, SourceCategory, UserIdentity
from agentshield.provenance.models import compute_content_hash

class AgentOutput(BaseModel):
    """Represents a generated output from an AI agent subject to security validation."""

    output_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    content: str
    agent_id: str = "default_agent"
    user_id: str
    tenant_id: str
    provenance_id: Optional[str] = None
    content_hash: str = ""
    output_type: str = "text"
    metadata: Dict[str, Any] = Field(default_factory=dict)
    timestamp: float = Field(default_factory=time.time)

    def model_post_init(self, __context: Any) -> None:
        if not self.content_hash and self.content:
            self.content_hash = compute_content_hash(self.content)

class OutputValidationResult(BaseModel):
    """Result of output security validation before external release."""

    output_id: Optional[str] = None
    valid: bool = False
    decision: SecurityDecision = SecurityDecision.DENY
    violations: List[str] = Field(default_factory=list)
    integrity_valid: bool = True
    provenance_valid: bool = True
    authorization_valid: bool = True
    sensitive_data_detected: bool = False
    policy_valid: bool = True
    reason: str = ""
    validation_time_ms: float = 0.0
    timestamp: float = Field(default_factory=time.time)

class ActionType(str, Enum):
    READ = "READ"
    WRITE = "WRITE"
    MEMORY_WRITE = "MEMORY_WRITE"
    DATA_EXPORT = "DATA_EXPORT"
    API_REQUEST = "API_REQUEST"
    TASK_EXECUTION = "TASK_EXECUTION"
    UNKNOWN = "UNKNOWN"

class AgentAction(BaseModel):
    """Represents a proposed action requested or generated by an AI agent."""

    action_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    agent_id: str = "default_agent"
    user_id: str
    tenant_id: str
    action_type: ActionType = ActionType.UNKNOWN
    target: str = ""
    parameters: Dict[str, Any] = Field(default_factory=dict)
    provenance_id: Optional[str] = None
    timestamp: float = Field(default_factory=time.time)
    metadata: Dict[str, Any] = Field(default_factory=dict)

class ActionValidationResult(BaseModel):
    """Result of proposed action security validation prior to any execution."""

    action_id: Optional[str] = None
    valid: bool = False
    decision: SecurityDecision = SecurityDecision.DENY
    violations: List[str] = Field(default_factory=list)
    authorization_valid: bool = True
    target_valid: bool = True
    parameters_valid: bool = True
    is_high_risk: bool = False
    reason: str = ""
    validation_time_ms: float = 0.0
    timestamp: float = Field(default_factory=time.time)
