"""
Output & Action Validation Engine for AgentShield.

Guarantees: AGENT OUTPUT MUST NOT AUTOMATICALLY BE TREATED AS SAFE JUST BECAUSE IT WAS GENERATED BY THE AGENT.
Validates output content, integrity, secrets, provenance, and action authorizations before release.
"""

import time
import re
from typing import List, Optional, Dict, Any, Tuple

from agentshield.context.models import UserIdentity, SecurityDecision, TrustLevel, SourceCategory
from agentshield.security.output_action_models import (
    AgentOutput,
    OutputValidationResult,
    AgentAction,
    ActionValidationResult,
    ActionType
)
from agentshield.security.secrets import SecretDetector
from agentshield.provenance.lineage import ProvenanceTracker
from agentshield.provenance.models import compute_content_hash
from agentshield.provenance.logger import AuditLogger
from agentshield.policies.engine import PolicyEngine

MAX_PARAM_SIZE: int = 5000

class OutputActionValidator:
    """
    Validates agent outputs and proposed actions before external release or execution approval.
    """

    def __init__(
        self,
        secret_detector: Optional[SecretDetector] = None,
        audit_logger: Optional[AuditLogger] = None,
        policy_engine: Optional[PolicyEngine] = None,
        max_param_size: int = MAX_PARAM_SIZE
    ):
        self.secret_detector = secret_detector or SecretDetector()
        self.audit_logger = audit_logger or AuditLogger()
        self.policy_engine = policy_engine or PolicyEngine()
        self.max_param_size = max_param_size

    def validate_output(
        self,
        output: AgentOutput,
        identity: Optional[UserIdentity] = None,
        tracker: Optional[ProvenanceTracker] = None
    ) -> OutputValidationResult:
        """
        Validates generated agent output before external release.
        """
        t0 = time.time()
        violations: List[str] = []

        # 1. Empty / Malformed Content Check
        if not output.content or output.content.strip() == "":
            elapsed = (time.time() - t0) * 1000.0
            return OutputValidationResult(
                output_id=output.output_id,
                valid=False,
                decision=SecurityDecision.DENY,
                reason="Empty or malformed output content",
                violations=["EMPTY_OUTPUT_CONTENT"],
                validation_time_ms=elapsed
            )

        # 2. Identity & Fail-Closed Checks
        target_user = output.user_id
        target_tenant = output.tenant_id

        if not target_user or target_user.strip() == "":
            violations.append("FAIL-CLOSED: Missing or empty user identity in output")
            elapsed = (time.time() - t0) * 1000.0
            return OutputValidationResult(
                output_id=output.output_id,
                valid=False,
                decision=SecurityDecision.DENY,
                authorization_valid=False,
                reason="Missing user identity in output",
                violations=violations,
                validation_time_ms=elapsed
            )

        if not target_tenant or target_tenant.strip() == "":
            violations.append("FAIL-CLOSED: Missing or empty tenant identity in output")
            elapsed = (time.time() - t0) * 1000.0
            return OutputValidationResult(
                output_id=output.output_id,
                valid=False,
                decision=SecurityDecision.DENY,
                authorization_valid=False,
                reason="Missing tenant identity in output",
                violations=violations,
                validation_time_ms=elapsed
            )

        if identity is not None:
            if not identity.user_id or not identity.tenant_id:
                violations.append("FAIL-CLOSED: Requesting UserIdentity incomplete")
                elapsed = (time.time() - t0) * 1000.0
                return OutputValidationResult(
                    output_id=output.output_id,
                    valid=False,
                    decision=SecurityDecision.DENY,
                    authorization_valid=False,
                    reason="Incomplete UserIdentity provided",
                    violations=violations,
                    validation_time_ms=elapsed
                )

            if identity.tenant_id != target_tenant:
                violations.append(f"CROSS-TENANT OUTPUT DENIED: Request tenant '{identity.tenant_id}' != Output tenant '{target_tenant}'")
                elapsed = (time.time() - t0) * 1000.0
                return OutputValidationResult(
                    output_id=output.output_id,
                    valid=False,
                    decision=SecurityDecision.DENY,
                    authorization_valid=False,
                    reason="Cross-tenant output release prohibited",
                    violations=violations,
                    validation_time_ms=elapsed
                )

            if identity.user_id != target_user and "admin" not in identity.roles:
                violations.append(f"CROSS-USER OUTPUT DENIED: Request user '{identity.user_id}' != Output user '{target_user}'")
                elapsed = (time.time() - t0) * 1000.0
                return OutputValidationResult(
                    output_id=output.output_id,
                    valid=False,
                    decision=SecurityDecision.DENY,
                    authorization_valid=False,
                    reason="Cross-user output release prohibited",
                    violations=violations,
                    validation_time_ms=elapsed
                )

        # 3. Content Hashing & Output Integrity Check
        computed_hash = compute_content_hash(output.content)
        integrity_ok = True
        if output.content_hash and output.content_hash != computed_hash:
            integrity_ok = False
            violations.append(f"OUTPUT HASH MISMATCH: Stored hash '{output.content_hash[:8]}...' != Computed hash '{computed_hash[:8]}...'")

        # 4. Provenance Verification
        provenance_ok = True
        if output.provenance_id:
            if tracker and tracker.get_provenance(output.provenance_id) is None:
                provenance_ok = False
                violations.append(f"INVALID PROVENANCE: Provenance ID '{output.provenance_id}' not found in lineage tracker")

        # 5. Secret / Sensitive Data Detection
        sec_res = self.secret_detector.detect_secrets(output.content)
        sensitive_ok = not sec_res["has_secrets"]
        if not sensitive_ok:
            violations.append(f"SENSITIVE DATA DETECTED in output: {sec_res.get('types', [])}")

        elapsed = (time.time() - t0) * 1000.0
        final_valid = (len(violations) == 0 and integrity_ok and provenance_ok and sensitive_ok)
        decision = SecurityDecision.ALLOW if final_valid else SecurityDecision.DENY

        res = OutputValidationResult(
            output_id=output.output_id,
            valid=final_valid,
            decision=decision,
            violations=violations,
            integrity_valid=integrity_ok,
            provenance_valid=provenance_ok,
            authorization_valid=True,
            sensitive_data_detected=not sensitive_ok,
            policy_valid=final_valid,
            reason="Output validated successfully" if final_valid else "Output failed security validation",
            validation_time_ms=elapsed
        )

        # Audit event recording without raw sensitive content
        self.audit_logger.log_event(
            "OUTPUT_VALIDATED" if final_valid else "OUTPUT_BLOCKED",
            {
                "output_id": output.output_id,
                "agent_id": output.agent_id,
                "user_id": target_user,
                "decision": decision.value,
                "reason": res.reason,
                "violations": res.violations,
                "provenance_id": output.provenance_id
            },
            tenant_id=target_tenant
        )

        return res

    def validate_action(
        self,
        action: AgentAction,
        identity: Optional[UserIdentity] = None,
        tracker: Optional[ProvenanceTracker] = None
    ) -> ActionValidationResult:
        """
        Validates a proposed agent action before any execution approval.
        """
        t0 = time.time()
        violations: List[str] = []

        # 1. Identity & Fail-Closed Checks
        target_user = action.user_id
        target_tenant = action.tenant_id

        if not target_user or target_user.strip() == "":
            violations.append("FAIL-CLOSED: Missing or empty user identity in action")
            elapsed = (time.time() - t0) * 1000.0
            return ActionValidationResult(
                action_id=action.action_id,
                valid=False,
                decision=SecurityDecision.DENY,
                authorization_valid=False,
                reason="Missing user identity in action",
                violations=violations,
                validation_time_ms=elapsed
            )

        if not target_tenant or target_tenant.strip() == "":
            violations.append("FAIL-CLOSED: Missing or empty tenant identity in action")
            elapsed = (time.time() - t0) * 1000.0
            return ActionValidationResult(
                action_id=action.action_id,
                valid=False,
                decision=SecurityDecision.DENY,
                authorization_valid=False,
                reason="Missing tenant identity in action",
                violations=violations,
                validation_time_ms=elapsed
            )

        if identity is not None:
            if not identity.user_id or not identity.tenant_id:
                violations.append("FAIL-CLOSED: Requesting UserIdentity incomplete")
                elapsed = (time.time() - t0) * 1000.0
                return ActionValidationResult(
                    action_id=action.action_id,
                    valid=False,
                    decision=SecurityDecision.DENY,
                    authorization_valid=False,
                    reason="Incomplete UserIdentity provided",
                    violations=violations,
                    validation_time_ms=elapsed
                )

            if identity.tenant_id != target_tenant:
                violations.append(f"CROSS-TENANT ACTION DENIED: Request tenant '{identity.tenant_id}' != Action tenant '{target_tenant}'")
                elapsed = (time.time() - t0) * 1000.0
                return ActionValidationResult(
                    action_id=action.action_id,
                    valid=False,
                    decision=SecurityDecision.DENY,
                    authorization_valid=False,
                    reason="Cross-tenant action prohibited",
                    violations=violations,
                    validation_time_ms=elapsed
                )

            if identity.user_id != target_user and "admin" not in identity.roles:
                violations.append(f"CROSS-USER ACTION DENIED: Request user '{identity.user_id}' != Action user '{target_user}'")
                elapsed = (time.time() - t0) * 1000.0
                return ActionValidationResult(
                    action_id=action.action_id,
                    valid=False,
                    decision=SecurityDecision.DENY,
                    authorization_valid=False,
                    reason="Cross-user action prohibited",
                    violations=violations,
                    validation_time_ms=elapsed
                )

        # 2. Action Type Check
        if action.action_type == ActionType.UNKNOWN or not isinstance(action.action_type, ActionType):
            violations.append("INVALID ACTION TYPE: Action type is unknown or invalid")
            elapsed = (time.time() - t0) * 1000.0
            return ActionValidationResult(
                action_id=action.action_id,
                valid=False,
                decision=SecurityDecision.DENY,
                reason="Unknown or invalid action type",
                violations=violations,
                validation_time_ms=elapsed
            )

        # 3. Target Validation
        target_ok = True
        if not action.target or action.target.strip() == "":
            target_ok = False
            violations.append("MISSING ACTION TARGET: Action target scope is empty or missing")

        # 4. Parameters Validation
        params_ok = True
        if isinstance(action.parameters, dict):
            for k, v in action.parameters.items():
                val_str = str(v)
                if len(val_str) > self.max_param_size:
                    params_ok = False
                    violations.append(f"OVERSIZED PARAMETER: Parameter '{k}' length {len(val_str)} > limit {self.max_param_size}")
        else:
            params_ok = False
            violations.append("INVALID PARAMETERS: Action parameters must be a dictionary")

        # 5. High-Risk Action Check
        high_risk_actions = [ActionType.DATA_EXPORT, ActionType.MEMORY_WRITE, ActionType.TASK_EXECUTION]
        is_high_risk = (action.action_type in high_risk_actions) or ("export" in action.target.lower() or "security" in action.target.lower())

        elapsed = (time.time() - t0) * 1000.0
        final_valid = (len(violations) == 0 and target_ok and params_ok)

        decision = SecurityDecision.DENY
        if final_valid:
            decision = SecurityDecision.REVIEW if is_high_risk else SecurityDecision.ALLOW

        res = ActionValidationResult(
            action_id=action.action_id,
            valid=final_valid,
            decision=decision,
            violations=violations,
            authorization_valid=True,
            target_valid=target_ok,
            parameters_valid=params_ok,
            is_high_risk=is_high_risk,
            reason="High-risk action requires human review" if (final_valid and is_high_risk) else ("Action authorized and validated" if final_valid else "Action validation failed"),
            validation_time_ms=elapsed
        )

        # Audit event recording without raw sensitive parameters
        self.audit_logger.log_event(
            "ACTION_APPROVED" if (final_valid and decision == SecurityDecision.ALLOW) else ("ACTION_REVIEW" if decision == SecurityDecision.REVIEW else "ACTION_BLOCKED"),
            {
                "action_id": action.action_id,
                "agent_id": action.agent_id,
                "user_id": target_user,
                "action_type": action.action_type.value,
                "target": action.target,
                "decision": decision.value,
                "reason": res.reason
            },
            tenant_id=target_tenant
        )

        return res

    def extract_and_validate_actions(
        self,
        output: AgentOutput,
        identity: Optional[UserIdentity] = None,
        tracker: Optional[ProvenanceTracker] = None
    ) -> List[ActionValidationResult]:
        """
        Parses textual agent output for proposed actions and evaluates each through validate_action().
        NOTE: This performs security validation ONLY; NO external actions are executed.
        """
        results: List[ActionValidationResult] = []

        # Scan content for action proposals
        pattern = r"(?i)proposed\s+action:\s*([A-Z_]+)\s+target:\s*([^\n]+)"
        matches = re.findall(pattern, output.content)

        for act_str, target_str in matches:
            act_type = ActionType.UNKNOWN
            try:
                act_type = ActionType(act_str.strip())
            except ValueError:
                act_type = ActionType.UNKNOWN

            proposed = AgentAction(
                agent_id=output.agent_id,
                user_id=output.user_id,
                tenant_id=output.tenant_id,
                action_type=act_type,
                target=target_str.strip(),
                provenance_id=output.provenance_id
            )
            val_res = self.validate_action(proposed, identity=identity, tracker=tracker)
            results.append(val_res)

        return results
